/** Catalogue upload genre catalogue (multi-select). */
export const CATALOGUE_GENRES = [
  // Core
  "Action",
  "Adventure",
  "Animation",
  "Anime",
  "Biography",
  "Comedy",
  "Crime",
  "Documentary",
  "Drama",
  "Family",
  "Fantasy",
  "History",
  "Horror",
  "Music",
  "Musical",
  "Mystery",
  "Romance",
  "Sci-Fi",
  "Sport",
  "Thriller",
  "War",
  "Western",
  // Tone / form
  "Dark Comedy",
  "Romantic Comedy",
  "Satire",
  "Parody",
  "Slapstick",
  "Coming-of-Age",
  "Slice of Life",
  "Anthology",
  "Experimental",
  "Avant-Garde",
  "Art House",
  "Indie",
  "Short Form",
  "Feature",
  "Miniseries",
  "Limited Series",
  "Reality",
  "Unscripted",
  "Variety",
  "Talk Show",
  "Game Show",
  "Sketch Comedy",
  "Stand-Up",
  "Live Performance",
  "Concert Film",
  "Music Video",
  "Podcast",
  "Interview",
  "News / Current Affairs",
  // Subgenres
  "Action-Comedy",
  "Action-Thriller",
  "Psychological Thriller",
  "Political Thriller",
  "Conspiracy Thriller",
  "Legal Drama",
  "Medical Drama",
  "Police Procedural",
  "Detective",
  "Noir",
  "Neo-Noir",
  "Heist",
  "Spy / Espionage",
  "Survival",
  "Disaster",
  "Found Footage",
  "Supernatural",
  "Paranormal",
  "Ghost Story",
  "Vampire",
  "Zombie",
  "Monster",
  "Creature Feature",
  "Slasher",
  "Body Horror",
  "Folk Horror",
  "Gothic",
  "Mythology",
  "Fairy Tale",
  "Sword & Sorcery",
  "Epic Fantasy",
  "Urban Fantasy",
  "Space Opera",
  "Hard Sci-Fi",
  "Cyberpunk",
  "Steampunk",
  "Dystopian",
  "Utopian",
  "Post-Apocalyptic",
  "Time Travel",
  "Alternate History",
  "Superhero",
  "Martial Arts",
  "Wuxia",
  "Samurai",
  "Mecha",
  "Kaiju",
  // Nature & factual
  "Nature",
  "Wildlife",
  "Natural History",
  "Environment",
  "Conservation",
  "Science",
  "Technology",
  "Space / Astronomy",
  "Ocean / Marine",
  "Travel",
  "Adventure Travel",
  "Expedition",
  "Food & Culinary",
  "Lifestyle",
  "Home & Garden",
  "Fashion",
  "Design",
  "Architecture",
  "Art & Culture",
  "Photography",
  "True Crime",
  "Investigative",
  "Social Issue",
  "Social Commentary",
  "Politics",
  "Human Rights",
  "Education",
  "How-To / Instructional",
  "Faith & Spirituality",
  "Religion",
  "Philosophy",
  "Health & Wellness",
  "Mental Health",
  "Disability Stories",
  "LGBTQ+",
  "Women's Stories",
  "Youth / Teen",
  "Children",
  "Kids & Family",
  "Educational Kids",
  // Sports & competition
  "Sports Drama",
  "Sports Documentary",
  "Football / Soccer",
  "Rugby",
  "Cricket",
  "Athletics",
  "Combat Sports",
  "Motorsport",
  "Extreme Sports",
  "Esports",
  // Romance & relationships
  "Period Romance",
  "Contemporary Romance",
  "Love Story",
  "Melodrama",
  "Soap",
  "Telenovela",
  // African / regional
  "Afro-Futurism",
  "Afro-Fantasy",
  "African Cinema",
  "Nollywood",
  "South African",
  "Township Drama",
  "Township Comedy",
  "Kasi Story",
  "Oral Tradition / Folklore",
  "Indigenous Stories",
  "Pan-African",
  "Diaspora",
  "Colonial History",
  "Liberation Struggle",
  "Apartheid Stories",
  "Ubuntu Stories",
  // Period & historical
  "Period Drama",
  "Historical Drama",
  "Costume Drama",
  "Biopic",
  "Memoir",
  "Autobiography",
  "War Documentary",
  "Military",
  // Feel / audience
  "Feel-Good",
  "Inspirational",
  "Motivational",
  "Tearjerker",
  "Whodunnit",
  "Courtroom",
  "Workplace",
  "Campus / School",
  "Road Movie",
  "Buddy Film",
  "Ensemble",
  "Mockumentary",
  "Meta / Self-Referential",
  "Silent / Mostly Silent",
  "Black & White",
  "Stop-Motion",
  "Claymation",
  "3D Animation",
  "2D Animation",
  "Mixed Media",
  "VR / Immersive",
  "Interactive",
  "Other",
] as const;

export type CatalogueGenre = (typeof CATALOGUE_GENRES)[number];
