import type { BudgetDepartment } from "@/lib/budget-engine";

export const EXPENSE_CATEGORIES = [
  "CAST",
  "CREW",
  "EQUIPMENT",
  "LOCATIONS",
  "ART_DEPARTMENT",
  "WARDROBE_MAKEUP",
  "SOUND",
  "POST_PRODUCTION",
  "TRANSPORT_LOGISTICS",
  "CATERING",
  "LEGAL",
  "INSURANCE",
  "MARKETING",
  "PAYROLL",
  "SOFTWARE",
  "MEDICAL",
  "SECURITY",
  "MISCELLANEOUS",
] as const;

export type ExpenseCategory = (typeof EXPENSE_CATEGORIES)[number];

export type ExpensePaymentMethod = "CASH" | "TRANSFER" | "CARD" | "MOBILE" | "PETTY_CASH" | "CREDIT_CARD" | "OTHER";
export type ExpenseApprovalStatus = "PENDING" | "APPROVED" | "REJECTED";
export type ExpensePaymentStatus = "UNPAID" | "PARTIAL" | "PAID";

export type ExpenseMeta = {
  title?: string | null;
  category?: ExpenseCategory | string | null;
  sceneId?: string | null;
  shootDayId?: string | null;
  paymentMethod?: ExpensePaymentMethod | null;
  notes?: string | null;
  receiptUrls?: string[];
  paymentProofUrls?: string[];
  fundingSource?: string | null;
  fundingSourceId?: string | null;
  approvalStatus?: ExpenseApprovalStatus;
  approvalByUserId?: string | null;
  approvalAt?: string | null;
  paymentStatus?: ExpensePaymentStatus;
  paymentDueAt?: string | null;
  linkedContractId?: string | null;
  linkedEquipmentPlanItemId?: string | null;
  linkedLocationBookingId?: string | null;
  linkedTaskId?: string | null;
  linkedBudgetLineId?: string | null;
  linkedPurchaseOrderId?: string | null;
  linkedVendorId?: string | null;
  linkedPayrollLineItemId?: string | null;
  autoGeneratedFrom?: string | null;
  receiptNumber?: string | null;
  invoiceNumber?: string | null;
  vatAmount?: number | null;
  subtotal?: number | null;
  currency?: string | null;
  ocrConfidence?: number | null;
  ocrRawText?: string | null;
  duplicateOfId?: string | null;
  softDeleted?: boolean;
  history?: Array<{
    at: string;
    byUserId: string | null;
    action: string;
    patch?: Record<string, unknown>;
  }>;
};

export type ParsedExpenseRow = {
  id: string;
  projectId: string;
  budgetLineId: string | null;
  department: string | null;
  vendor: string | null;
  description: string;
  amount: number;
  spentAt: string;
  createdAt: string;
  createdBy: { id: string; name: string | null; email: string | null } | null;
  meta: Required<Pick<ExpenseMeta, never>> & {
    title: string;
    category: string;
    sceneId: string | null;
    shootDayId: string | null;
    paymentMethod: string;
    notes: string | null;
    receiptUrls: string[];
    paymentProofUrls: string[];
    fundingSource: string | null;
    fundingSourceId: string | null;
    approvalStatus: ExpenseApprovalStatus;
    approvalByUserId: string | null;
    approvalAt: string | null;
    paymentStatus: ExpensePaymentStatus;
    paymentDueAt: string | null;
    linkedContractId: string | null;
    linkedEquipmentPlanItemId: string | null;
    linkedLocationBookingId: string | null;
    linkedTaskId: string | null;
    linkedBudgetLineId: string | null;
    autoGeneratedFrom: string | null;
    receiptNumber: string | null;
    invoiceNumber: string | null;
    vatAmount: number | null;
    subtotal: number | null;
    currency: string | null;
    ocrConfidence: number | null;
    ocrRawText: string | null;
    duplicateOfId: string | null;
    softDeleted: boolean;
    history: NonNullable<ExpenseMeta["history"]>;
  };
};

export function normalizeExpenseCategory(v: string | null | undefined): ExpenseCategory {
  const raw = (v ?? "").toUpperCase().replace(/\s+/g, "_").trim();
  if (raw.includes("CAST") || raw === "TALENT") return "CAST";
  if (raw.includes("LEGAL")) return "LEGAL";
  if (raw.includes("INSUR")) return "INSURANCE";
  if (raw.includes("MARKET")) return "MARKETING";
  if (raw.includes("PAYROLL") || raw.includes("FREELANCE")) return "PAYROLL";
  if (raw.includes("SOFTWARE") || raw.includes("SUBSCR")) return "SOFTWARE";
  if (raw.includes("MEDICAL")) return "MEDICAL";
  if (raw.includes("SECURITY")) return "SECURITY";
  if (raw.includes("EQUIP")) return "EQUIPMENT";
  if (raw.includes("LOCATION")) return "LOCATIONS";
  if (raw.includes("WARDROBE") || raw.includes("MAKEUP") || raw.includes("HAIR")) return "WARDROBE_MAKEUP";
  if (raw.includes("ART") || raw.includes("PROP") || raw.includes("SET")) return "ART_DEPARTMENT";
  if (raw.includes("SOUND")) return "SOUND";
  if (raw.includes("POST") || raw.includes("VFX") || raw.includes("EDIT")) return "POST_PRODUCTION";
  if (raw.includes("TRANSPORT") || raw.includes("LOGISTICS") || raw.includes("TRAVEL") || raw === "TRANSPORT") {
    return "TRANSPORT_LOGISTICS";
  }
  if (raw.includes("CATER") || raw.includes("FOOD")) return "CATERING";
  if (raw.includes("CREW")) return "CREW";
  if (raw === "MISCELLANEOUS" || raw === "MISC") return "MISCELLANEOUS";
  return "MISCELLANEOUS";
}

export function toBudgetDepartment(category: string): BudgetDepartment {
  const c = normalizeExpenseCategory(category);
  if (c === "LEGAL" || c === "INSURANCE" || c === "MARKETING" || c === "PAYROLL" || c === "SOFTWARE" || c === "MEDICAL" || c === "SECURITY" || c === "MISCELLANEOUS") {
    return "CREW";
  }
  return c as BudgetDepartment;
}

export function categoryLabel(cat: string): string {
  return cat.replaceAll("_", " ").replace(/\b\w/g, (c) => c.toUpperCase());
}

export function departmentHealth(pctUsed: number): "healthy" | "watch" | "over" {
  if (pctUsed > 100) return "over";
  if (pctUsed > 85) return "watch";
  return "healthy";
}
