import { prisma } from "@/lib/prisma";
import { parseEmbeddedMeta, embedMeta } from "@/lib/marketplace-profile-meta";
import { validateStorageUrlList } from "@/lib/storage-origin";
import {
  type ExpenseMeta,
  type ParsedExpenseRow,
  normalizeExpenseCategory,
  toBudgetDepartment,
} from "@/lib/expense-types";

export function asNum(v: unknown): number {
  const n = Number(v);
  return Number.isFinite(n) ? n : 0;
}

export function parseExpenseRow(
  e: {
    id: string;
    projectId: string;
    budgetLineId: string | null;
    department: string | null;
    vendor: string | null;
    description: string | null;
    amount: number;
    spentAt: Date;
    createdAt: Date;
    createdBy: { id: string; name: string | null; email: string | null } | null;
  },
): ParsedExpenseRow {
  const parsed = parseEmbeddedMeta<ExpenseMeta>(e.description);
  const meta = parsed.meta ?? {};
  const category = normalizeExpenseCategory(meta.category ?? e.department ?? "MISCELLANEOUS");
  return {
    id: e.id,
    projectId: e.projectId,
    budgetLineId: e.budgetLineId,
    department: e.department ?? category,
    vendor: e.vendor,
    description: parsed.plain ?? "",
    amount: e.amount,
    spentAt: e.spentAt.toISOString(),
    createdAt: e.createdAt.toISOString(),
    createdBy: e.createdBy,
    meta: {
      title: meta.title ?? parsed.plain ?? "Expense",
      category,
      sceneId: meta.sceneId ?? null,
      shootDayId: meta.shootDayId ?? null,
      paymentMethod: meta.paymentMethod ?? "OTHER",
      notes: meta.notes ?? null,
      receiptUrls: meta.receiptUrls ?? [],
      paymentProofUrls: meta.paymentProofUrls ?? [],
      fundingSource: meta.fundingSource ?? null,
      fundingSourceId: meta.fundingSourceId ?? null,
      approvalStatus: meta.approvalStatus ?? "PENDING",
      approvalByUserId: meta.approvalByUserId ?? null,
      approvalAt: meta.approvalAt ?? null,
      paymentStatus: meta.paymentStatus ?? "UNPAID",
      paymentDueAt: meta.paymentDueAt ?? null,
      linkedContractId: meta.linkedContractId ?? null,
      linkedEquipmentPlanItemId: meta.linkedEquipmentPlanItemId ?? null,
      linkedLocationBookingId: meta.linkedLocationBookingId ?? null,
      linkedCateringBookingId: meta.linkedCateringBookingId ?? null,
      linkedMarketplaceTransactionId: meta.linkedMarketplaceTransactionId ?? null,
      linkedTaskId: meta.linkedTaskId ?? null,
      linkedBudgetLineId: meta.linkedBudgetLineId ?? e.budgetLineId,
      autoGeneratedFrom: meta.autoGeneratedFrom ?? null,
      receiptNumber: meta.receiptNumber ?? null,
      invoiceNumber: meta.invoiceNumber ?? null,
      vatAmount: meta.vatAmount ?? null,
      subtotal: meta.subtotal ?? null,
      currency: meta.currency ?? "ZAR",
      ocrConfidence: meta.ocrConfidence ?? null,
      ocrRawText: meta.ocrRawText ?? null,
      duplicateOfId: meta.duplicateOfId ?? null,
      softDeleted: meta.softDeleted ?? false,
      history: meta.history ?? [],
    },
  };
}

export type CreateExpenseInput = {
  projectId: string;
  userId: string;
  amount: number;
  title?: string | null;
  description?: string | null;
  category?: string | null;
  department?: string | null;
  vendor?: string | null;
  vendorId?: string | null;
  purchaseOrderId?: string | null;
  pettyCashFundId?: string | null;
  budgetLineId?: string | null;
  sceneId?: string | null;
  shootDayId?: string | null;
  paymentMethod?: ExpenseMeta["paymentMethod"];
  notes?: string | null;
  receiptUrls?: string[];
  paymentProofUrls?: string[];
  fundingSource?: string | null;
  fundingSourceId?: string | null;
  approvalStatus?: ExpenseMeta["approvalStatus"];
  paymentStatus?: ExpenseMeta["paymentStatus"];
  paymentDueAt?: string | null;
  spentAt?: string | Date | null;
  linkedContractId?: string | null;
  linkedEquipmentPlanItemId?: string | null;
  linkedLocationBookingId?: string | null;
  linkedCateringBookingId?: string | null;
  linkedMarketplaceTransactionId?: string | null;
  linkedTaskId?: string | null;
  linkedBudgetLineId?: string | null;
  autoGeneratedFrom?: string | null;
  receiptNumber?: string | null;
  invoiceNumber?: string | null;
  vatAmount?: number | null;
  subtotal?: number | null;
  currency?: string | null;
  ocrConfidence?: number | null;
  ocrRawText?: string | null;
  skipDuplicateCheck?: boolean;
  forceCreate?: boolean;
};

export function detectDuplicateCandidates(
  rows: ParsedExpenseRow[],
  candidate: { amount: number; vendor?: string | null; spentAt?: Date; receiptNumber?: string | null; invoiceNumber?: string | null },
): ParsedExpenseRow[] {
  const day = candidate.spentAt?.toISOString().slice(0, 10);
  return rows.filter((e) => {
    if (e.meta.softDeleted) return false;
    if (candidate.receiptNumber && e.meta.receiptNumber === candidate.receiptNumber) return true;
    if (candidate.invoiceNumber && e.meta.invoiceNumber === candidate.invoiceNumber) return true;
    const sameAmount = Math.abs(e.amount - candidate.amount) < 0.01;
    const sameVendor =
      candidate.vendor &&
      e.vendor &&
      e.vendor.toLowerCase().trim() === candidate.vendor.toLowerCase().trim();
    const sameDay = day && e.spentAt.slice(0, 10) === day;
    return sameAmount && sameVendor && sameDay;
  });
}

export async function createProductionExpense(input: CreateExpenseInput) {
  const category = normalizeExpenseCategory(input.category ?? input.department);
  const meta: ExpenseMeta = {
    title: input.title ?? input.description ?? "Expense",
    category,
    sceneId: input.sceneId ?? null,
    shootDayId: input.shootDayId ?? null,
    paymentMethod: input.paymentMethod ?? "OTHER",
    notes: input.notes ?? null,
    receiptUrls: input.receiptUrls ?? [],
    paymentProofUrls: input.paymentProofUrls ?? [],
    fundingSource: input.fundingSource ?? null,
    fundingSourceId: input.fundingSourceId ?? null,
    approvalStatus: input.approvalStatus ?? "PENDING",
    paymentStatus: input.paymentStatus ?? "UNPAID",
    paymentDueAt: input.paymentDueAt ?? null,
    linkedContractId: input.linkedContractId ?? null,
    linkedEquipmentPlanItemId: input.linkedEquipmentPlanItemId ?? null,
    linkedLocationBookingId: input.linkedLocationBookingId ?? null,
    linkedCateringBookingId: input.linkedCateringBookingId ?? null,
    linkedMarketplaceTransactionId: input.linkedMarketplaceTransactionId ?? null,
    linkedTaskId: input.linkedTaskId ?? null,
    linkedBudgetLineId: input.linkedBudgetLineId ?? input.budgetLineId ?? null,
    autoGeneratedFrom: input.autoGeneratedFrom ?? null,
    receiptNumber: input.receiptNumber ?? null,
    invoiceNumber: input.invoiceNumber ?? null,
    vatAmount: input.vatAmount ?? null,
    subtotal: input.subtotal ?? null,
    currency: input.currency ?? "ZAR",
    ocrConfidence: input.ocrConfidence ?? null,
    ocrRawText: input.ocrRawText ?? null,
    history: [{ at: new Date().toISOString(), byUserId: input.userId, action: "CREATE" }],
  };

  if (input.pettyCashFundId && input.paymentMethod === "PETTY_CASH") {
    const { deductPettyCash } = await import("@/lib/financial-ops/petty-cash-service");
    const deduct = await deductPettyCash(input.pettyCashFundId, input.amount);
    if (deduct.error) throw new Error(deduct.error);
  }

  const receiptErr = validateStorageUrlList(meta.receiptUrls ?? [], "receiptUrls");
  if (receiptErr) throw new Error(receiptErr);
  const proofErr = validateStorageUrlList(meta.paymentProofUrls ?? [], "paymentProofUrls");
  if (proofErr) throw new Error(proofErr);

  let duplicateWarnings: ParsedExpenseRow[] = [];
  if (!input.skipDuplicateCheck && !input.forceCreate) {
    const existing = await prisma.productionExpense.findMany({
      where: { projectId: input.projectId },
      include: { createdBy: { select: { id: true, name: true, email: true } } },
    });
    const parsed = existing.map(parseExpenseRow);
    duplicateWarnings = detectDuplicateCandidates(parsed, {
      amount: input.amount,
      vendor: input.vendor,
      spentAt: input.spentAt ? new Date(input.spentAt) : new Date(),
      receiptNumber: input.receiptNumber,
      invoiceNumber: input.invoiceNumber,
    });
    if (duplicateWarnings.length > 0) {
      meta.duplicateOfId = duplicateWarnings[0]!.id;
    }
  }

  const expense = await prisma.productionExpense.create({
    data: {
      projectId: input.projectId,
      budgetLineId: input.budgetLineId ?? input.linkedBudgetLineId ?? null,
      vendorId: input.vendorId ?? null,
      purchaseOrderId: input.purchaseOrderId ?? null,
      pettyCashFundId: input.pettyCashFundId ?? null,
      department: toBudgetDepartment(category),
      vendor: input.vendor ?? null,
      description: embedMeta(input.description ?? null, meta as Record<string, unknown>),
      amount: input.amount,
      spentAt: input.spentAt ? new Date(input.spentAt) : new Date(),
      createdById: input.userId,
    },
    include: { createdBy: { select: { id: true, name: true, email: true } } },
  });

  return { expense: parseExpenseRow(expense), duplicateWarnings };
}

export async function updateProductionExpense(
  projectId: string,
  expenseId: string,
  userId: string,
  patch: {
    amount?: number;
    department?: string | null;
    vendor?: string | null;
    description?: string | null;
    spentAt?: string;
    meta?: Partial<ExpenseMeta>;
  },
) {
  const existing = await prisma.productionExpense.findFirst({
    where: { id: expenseId, projectId },
    include: { createdBy: { select: { id: true, name: true, email: true } } },
  });
  if (!existing) throw new Error("Expense not found");

  const parsed = parseEmbeddedMeta<ExpenseMeta>(existing.description);
  const prevMeta = parsed.meta ?? {};
  const history = [...(prevMeta.history ?? [])];
  history.push({
    at: new Date().toISOString(),
    byUserId: userId,
    action: "PATCH",
    patch: (patch.meta ?? {}) as Record<string, unknown>,
  });

  const mergedMeta: ExpenseMeta = {
    ...prevMeta,
    ...(patch.meta ?? {}),
    history: history.slice(-50),
  };

  if (patch.meta?.approvalStatus === "APPROVED" && !mergedMeta.approvalAt) {
    mergedMeta.approvalByUserId = userId;
    mergedMeta.approvalAt = new Date().toISOString();
  }

  const receiptErr = validateStorageUrlList(mergedMeta.receiptUrls ?? [], "receiptUrls");
  if (receiptErr) throw new Error(receiptErr);
  const proofErr = validateStorageUrlList(mergedMeta.paymentProofUrls ?? [], "paymentProofUrls");
  if (proofErr) throw new Error(proofErr);

  const category = normalizeExpenseCategory(mergedMeta.category ?? patch.department ?? existing.department);

  const expense = await prisma.productionExpense.update({
    where: { id: expenseId },
    data: {
      ...(patch.amount !== undefined ? { amount: patch.amount } : {}),
      ...(patch.department !== undefined || patch.meta?.category
        ? { department: toBudgetDepartment(category) }
        : {}),
      ...(patch.vendor !== undefined ? { vendor: patch.vendor } : {}),
      ...(patch.spentAt !== undefined ? { spentAt: patch.spentAt ? new Date(patch.spentAt) : existing.spentAt } : {}),
      ...(patch.description !== undefined || patch.meta !== undefined
        ? {
            description: embedMeta(
              patch.description ?? parsed.plain,
              { ...mergedMeta, category } as Record<string, unknown>,
            ),
          }
        : {}),
    },
    include: { createdBy: { select: { id: true, name: true, email: true } } },
  });

  return parseExpenseRow(expense);
}

export async function softDeleteProductionExpense(projectId: string, expenseId: string, userId: string) {
  return updateProductionExpense(projectId, expenseId, userId, {
    meta: { softDeleted: true },
  });
}

export async function findExpenseByIdOrTitle(projectId: string, id?: string | null, title?: string | null) {
  if (id) {
    return prisma.productionExpense.findFirst({
      where: { id, projectId },
      include: { createdBy: { select: { id: true, name: true, email: true } } },
    });
  }
  if (!title?.trim()) return null;
  const rows = await prisma.productionExpense.findMany({
    where: { projectId },
    include: { createdBy: { select: { id: true, name: true, email: true } } },
  });
  const needle = title.trim().toLowerCase();
  return (
    rows.find((r) => {
      const p = parseEmbeddedMeta<ExpenseMeta>(r.description);
      const t = (p.meta?.title ?? p.plain ?? "").toLowerCase();
      return t === needle || t.includes(needle);
    }) ?? null
  );
}

export function buildExpenseDashboard(
  expenseRows: ParsedExpenseRow[],
  budgetLines: Array<{ department: string | null; total: number | null; quantity: number | null; unitCost: number | null }>,
  totalPlanned: number,
  fundingLimit: number,
  shootDaysCount: number,
) {
  const active = expenseRows.filter((e) => !e.meta.softDeleted);
  const budgetByDept = budgetLines.reduce(
    (acc, line) => {
      const key = normalizeExpenseCategory(line.department ?? "MISCELLANEOUS");
      acc[key] = (acc[key] ?? 0) + asNum(line.total ?? asNum(line.quantity) * asNum(line.unitCost));
      return acc;
    },
    {} as Record<string, number>,
  );

  const actualByDept = active.reduce((acc, e) => {
    const key = normalizeExpenseCategory(e.meta.category);
    acc[key] = (acc[key] ?? 0) + asNum(e.amount);
    return acc;
  }, {} as Record<string, number>);

  const totalSpend = active.reduce((s, e) => s + asNum(e.amount), 0);
  const pendingApproval = active.filter((e) => e.meta.approvalStatus === "PENDING");
  const approvedUnpaid = active.filter((e) => e.meta.approvalStatus === "APPROVED" && e.meta.paymentStatus !== "PAID");
  const committedCosts = approvedUnpaid.reduce((s, e) => s + e.amount, 0);
  const pendingAmount = pendingApproval.reduce((s, e) => s + e.amount, 0);
  const reimbursable = active.filter(
    (e) => e.meta.paymentMethod === "CASH" || e.meta.paymentMethod === "PETTY_CASH",
  );
  const pettyCashSpent = reimbursable.reduce((s, e) => s + e.amount, 0);
  const cardSpent = active
    .filter((e) => e.meta.paymentMethod === "CARD" || e.meta.paymentMethod === "CREDIT_CARD")
    .reduce((s, e) => s + e.amount, 0);
  const missingReceipts = active.filter((e) => e.meta.receiptUrls.length === 0 && e.amount > 0).length;
  const duplicates = active.filter((e) => e.meta.duplicateOfId).length;

  const burnByDay = Object.entries(
    active.reduce((acc, e) => {
      const key = e.spentAt.slice(0, 10);
      acc[key] = (acc[key] ?? 0) + asNum(e.amount);
      return acc;
    }, {} as Record<string, number>),
  ).sort((a, b) => a[0].localeCompare(b[0]));

  const avgBurn = burnByDay.length > 0 ? burnByDay.reduce((s, [, a]) => s + a, 0) / burnByDay.length : 0;
  const daysRemaining = Math.max(1, shootDaysCount);
  const forecastSpend = totalSpend + avgBurn * daysRemaining;
  const burnRate = totalPlanned > 0 ? totalSpend / totalPlanned : 0;
  const budgetHealthScore = Math.max(0, Math.min(100, Math.round((1 - burnRate) * 100)));
  const variancePct = totalPlanned > 0 ? ((totalSpend - totalPlanned) / totalPlanned) * 100 : 0;
  const financialRiskScore = Math.min(
    100,
    Math.round(
      (variancePct > 0 ? variancePct * 2 : 0) +
        pendingApproval.length * 3 +
        missingReceipts * 2 +
        duplicates * 5,
    ),
  );

  const now = new Date();
  const weekAgo = new Date(now.getTime() - 7 * 86400000);
  const monthAgo = new Date(now.getTime() - 30 * 86400000);
  const dailySpend = active
    .filter((e) => e.spentAt.slice(0, 10) === now.toISOString().slice(0, 10))
    .reduce((s, e) => s + e.amount, 0);
  const weeklySpend = active.filter((e) => new Date(e.spentAt) >= weekAgo).reduce((s, e) => s + e.amount, 0);
  const monthlySpend = active.filter((e) => new Date(e.spentAt) >= monthAgo).reduce((s, e) => s + e.amount, 0);

  const topCostDrivers = Object.entries(actualByDept)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 8)
    .map(([category, amount]) => ({ category, amount }));

  const largeTransactions = [...active].sort((a, b) => b.amount - a.amount).slice(0, 5);

  const upcomingPayments = active
    .filter((e) => e.meta.paymentDueAt && e.meta.paymentStatus !== "PAID")
    .sort((a, b) => (a.meta.paymentDueAt ?? "").localeCompare(b.meta.paymentDueAt ?? ""))
    .slice(0, 10);

  const comparisonByDepartment = Object.keys({ ...budgetByDept, ...actualByDept }).map((dept) => {
    const budgeted = budgetByDept[dept] ?? 0;
    const actual = actualByDept[dept] ?? 0;
    const committed = approvedUnpaid
      .filter((e) => normalizeExpenseCategory(e.meta.category) === dept)
      .reduce((s, e) => s + e.amount, 0);
    const remaining = budgeted - actual;
    const pctUsed = budgeted > 0 ? (actual / budgeted) * 100 : actual > 0 ? 100 : 0;
    const forecast = budgeted > 0 ? actual + committed + avgBurn * 0.15 * budgeted : actual;
    return {
      key: dept,
      budgeted,
      actual,
      committed,
      remaining,
      variance: budgeted - actual,
      pctUsed,
      forecast,
      projectedOverrun: Math.max(0, forecast - budgeted),
      health: pctUsed > 100 ? "over" : pctUsed > 85 ? "watch" : "healthy",
    };
  });

  const aiInsights: string[] = [];
  if (totalPlanned > 0 && totalSpend > totalPlanned) {
    aiInsights.push(`Production is over budget by R${Math.round(totalSpend - totalPlanned).toLocaleString()}.`);
  }
  const worstDept = comparisonByDepartment.filter((d) => d.health === "over").sort((a, b) => b.actual - a.actual)[0];
  if (worstDept) {
    aiInsights.push(`${worstDept.key.replaceAll("_", " ")} is overspending — review recent vendor payments.`);
  }
  if (missingReceipts > 0) {
    aiInsights.push(`${missingReceipts} expense(s) are missing receipt attachments.`);
  }
  if (duplicates > 0) {
    aiInsights.push(`${duplicates} possible duplicate expense(s) flagged — verify before payment.`);
  }
  if (avgBurn > 0 && forecastSpend > totalPlanned && totalPlanned > 0) {
    aiInsights.push(
      `At current burn rate (R${Math.round(avgBurn).toLocaleString()}/day), forecast final cost is R${Math.round(forecastSpend).toLocaleString()}.`,
    );
  }

  return {
    totalBudget: totalPlanned,
    totalSpend,
    remainingBudget: Math.max(0, totalPlanned - totalSpend),
    committedCosts,
    pendingExpenses: pendingApproval.length,
    pendingAmount,
    pendingApprovals: pendingApproval.length,
    reimbursableAmount: reimbursable.filter((e) => e.meta.paymentStatus !== "PAID").reduce((s, e) => s + e.amount, 0),
    pettyCashSpent,
    creditCardSpending: cardSpent,
    purchaseOrders: active.filter((e) => e.meta.linkedContractId || e.meta.invoiceNumber).length,
    outstandingInvoices: approvedUnpaid.length,
    cashOnHand: fundingLimit > 0 ? Math.max(0, fundingLimit - totalSpend) : null,
    dailySpend,
    weeklySpend,
    monthlySpend,
    forecastSpend,
    burnRateDaily: avgBurn,
    budgetHealthScore,
    financialRiskScore,
    variance: totalPlanned - totalSpend,
    variancePct,
    unpaidCount: active.filter((e) => e.meta.paymentStatus !== "PAID").length,
    missingReceipts,
    duplicateCount: duplicates,
    topCostDrivers,
    largeTransactions: largeTransactions.map((e) => ({
      id: e.id,
      title: e.meta.title,
      amount: e.amount,
      category: e.meta.category,
      vendor: e.vendor,
      spentAt: e.spentAt,
    })),
    upcomingPayments: upcomingPayments.map((e) => ({
      id: e.id,
      title: e.meta.title,
      amount: e.amount,
      dueAt: e.meta.paymentDueAt,
      vendor: e.vendor,
    })),
    recentActivity: [...active]
      .sort((a, b) => b.createdAt.localeCompare(a.createdAt))
      .slice(0, 15)
      .map((e) => ({
        id: e.id,
        title: e.meta.title,
        amount: e.amount,
        action: e.meta.history[e.meta.history.length - 1]?.action ?? "CREATE",
        at: e.createdAt,
      })),
    aiInsights,
    comparisonByDepartment,
    burnByDay: burnByDay.map(([date, amount]) => ({ date, amount })),
  };
}
