import { prisma } from "@/lib/prisma";
import { createProductionExpense } from "@/lib/expense-service";
import { parseMarketplaceBookingNote } from "@/lib/marketplace-booking-context";
import type { ExpenseCategory } from "@/lib/expense-types";
import type { MarketplaceEntityType, MarketplaceSettlementQuote } from "@/lib/payments/marketplace-settlement";
import { parseEmbeddedMeta } from "@/lib/marketplace-profile-meta";
import type { ExpenseMeta } from "@/lib/expense-types";

type EntityExpenseContext = {
  projectId: string | null;
  vendor: string;
  title: string;
  category: ExpenseCategory;
  spentAt: Date;
  linkedLocationBookingId?: string | null;
  linkedCateringBookingId?: string | null;
  notes?: string | null;
};

async function loadEntityExpenseContext(
  entityType: MarketplaceEntityType,
  entityId: string,
): Promise<EntityExpenseContext | null> {
  if (entityType === "EquipmentRequest") {
    const row = await prisma.equipmentRequest.findUnique({
      where: { id: entityId },
      include: { equipment: { select: { companyName: true, category: true } } },
    });
    if (!row) return null;
    const ctx = parseMarketplaceBookingNote(row.note);
    return {
      projectId: ctx.projectId,
      vendor: row.equipment.companyName,
      title: `Equipment rental — ${row.equipment.category}`,
      category: "EQUIPMENT",
      spentAt: row.startDate ? new Date(row.startDate) : new Date(),
      notes: ctx.plainNote,
    };
  }

  if (entityType === "LocationBooking") {
    const row = await prisma.locationBooking.findUnique({
      where: { id: entityId },
      include: { location: { select: { name: true, city: true } } },
    });
    if (!row) return null;
    const ctx = parseMarketplaceBookingNote(row.note);
    return {
      projectId: ctx.projectId,
      vendor: row.location.name,
      title: `Location booking — ${row.location.city ?? row.location.name}`,
      category: "LOCATIONS",
      spentAt: row.startDate ? new Date(row.startDate) : new Date(),
      linkedLocationBookingId: row.id,
      notes: ctx.plainNote,
    };
  }

  if (entityType === "CateringBooking") {
    const row = await prisma.cateringBooking.findUnique({
      where: { id: entityId },
      include: { cateringCompany: { select: { companyName: true } } },
    });
    if (!row) return null;
    const ctx = parseMarketplaceBookingNote(row.note);
    return {
      projectId: ctx.projectId,
      vendor: row.cateringCompany.companyName,
      title: `On-set catering${row.headCount ? ` (${row.headCount} people)` : ""}`,
      category: "CATERING",
      spentAt: row.eventDate ? new Date(row.eventDate) : new Date(),
      linkedCateringBookingId: row.id,
      notes: ctx.plainNote,
    };
  }

  return null;
}

async function expenseAlreadySynced(autoGeneratedFrom: string, projectId: string) {
  const rows = await prisma.productionExpense.findMany({
    where: { projectId },
    select: { description: true },
    take: 500,
    orderBy: { createdAt: "desc" },
  });
  return rows.some((row) => {
    const parsed = parseEmbeddedMeta<ExpenseMeta>(row.description);
    return parsed.meta?.autoGeneratedFrom === autoGeneratedFrom;
  });
}

/** Record a production expense when a marketplace booking is paid (equipment, location, catering). */
export async function syncMarketplacePaymentToExpense(
  quote: MarketplaceSettlementQuote,
  transactionId: string,
): Promise<{ created: boolean; expenseId?: string; reason?: string }> {
  if (
    quote.entityType !== "EquipmentRequest" &&
    quote.entityType !== "LocationBooking" &&
    quote.entityType !== "CateringBooking"
  ) {
    return { created: false, reason: "entity_type_not_expensable" };
  }

  const ctx = await loadEntityExpenseContext(quote.entityType, quote.entityId);
  if (!ctx?.projectId) {
    return { created: false, reason: "no_project_linked" };
  }

  const autoGeneratedFrom = `marketplace:${quote.entityType}:${quote.entityId}`;
  if (await expenseAlreadySynced(autoGeneratedFrom, ctx.projectId)) {
    return { created: false, reason: "already_synced" };
  }

  const result = await createProductionExpense({
    projectId: ctx.projectId,
    userId: quote.buyerUserId,
    amount: quote.baseAmount,
    title: ctx.title,
    description: ctx.notes ?? ctx.title,
    category: ctx.category,
    vendor: ctx.vendor,
    paymentMethod: "TRANSFER",
    paymentStatus: "PAID",
    approvalStatus: "APPROVED",
    spentAt: ctx.spentAt,
    linkedLocationBookingId: ctx.linkedLocationBookingId ?? null,
    linkedCateringBookingId: ctx.linkedCateringBookingId ?? null,
    linkedMarketplaceTransactionId: transactionId,
    notes: `Story Time marketplace payment (txn ${transactionId})`,
    autoGeneratedFrom,
    skipDuplicateCheck: true,
    forceCreate: true,
  });

  return { created: true, expenseId: result.expense.id };
}
