/**
 * Industry-standard cast & crew credit titles for catalogue upload.
 * Labels use common on-screen abbreviations (DOP, 1st AD, etc.) plus full titles.
 */

export type UploadCreditRole = {
  /** Stored on ContentCrewMember.role */
  value: string;
  /** Shown in dropdown */
  label: string;
};

export type UploadCreditRoleGroup = {
  category: string;
  roles: UploadCreditRole[];
};

function role(abbrev: string, full: string): UploadCreditRole {
  const value = abbrev === full ? full : `${abbrev} — ${full}`;
  return { value, label: value };
}

function r(full: string): UploadCreditRole {
  return { value: full, label: full };
}

export const UPLOAD_CREDIT_ROLE_GROUPS: UploadCreditRoleGroup[] = [
  {
    category: "Cast — Principal",
    roles: [
      r("Lead Actor"),
      r("Lead Actress"),
      r("Leading Role"),
      r("Co-Lead Actor"),
      r("Co-Lead Actress"),
      r("Co-Star"),
      r("Title Role"),
      r("Protagonist"),
      r("Antagonist"),
      r("Series Regular"),
      r("Series Lead"),
      r("Recurring Guest"),
      r("Recurring Character"),
      r("Guest Star"),
      r("Special Guest Star"),
      r("Cameo"),
      r("Special Appearance"),
      r("Narrator"),
      r("Voice Narrator"),
      r("Presenter"),
      r("Co-Presenter"),
      r("Host"),
      r("Co-Host"),
      r("Anchor"),
      r("Correspondent"),
      r("Interviewer"),
      r("Podcast Host"),
      r("Podcast Guest"),
    ],
  },
  {
    category: "Cast — Supporting & ensemble",
    roles: [
      r("Supporting Actor"),
      r("Supporting Actress"),
      r("Supporting Role"),
      r("Featured Actor"),
      r("Featured Actress"),
      r("Featured Extra"),
      r("Day Player"),
      r("Under-Five"),
      r("Bit Part"),
      r("Background Performer"),
      r("Extra"),
      r("Atmosphere"),
      r("Ensemble Cast"),
      r("Chorus / Ensemble"),
      r("Choir Member"),
      r("Dancer"),
      r("Principal Dancer"),
      r("Background Dancer"),
      r("Singer"),
      r("Background Vocalist"),
      r("Voice Actor"),
      r("Voice Actress"),
      r("Additional Voices"),
      r("ADR Loop Group"),
      r("Motion Capture Performer"),
      r("Performance Capture"),
      r("Child Actor"),
      r("Child Actress"),
      r("Teen Actor"),
      r("Teen Actress"),
      r("Baby / Infant Talent"),
      r("Elderly Talent"),
      r("Non-Speaking Role"),
    ],
  },
  {
    category: "Cast — Specialty & stand-ins",
    roles: [
      r("Stand-In"),
      r("Photo Double"),
      r("Body Double"),
      r("Stunt Double"),
      r("Utility Stunt"),
      r("Stunt Performer"),
      r("Fight Performer"),
      r("Precision Driver"),
      r("Dialect Talent"),
      r("Hand Model"),
      r("Foot Model"),
      r("Body Model"),
      r("Crowd Cast"),
      r("Special Skills Extra"),
      r("Military Extra"),
      r("Period Extra"),
      r("Lookalike"),
    ],
  },
  {
    category: "Directing",
    roles: [
      r("Director"),
      r("Co-Director"),
      r("Assistant Director (Director's Team)"),
      role("2nd Unit Dir.", "Second Unit Director"),
      role("3rd Unit Dir.", "Third Unit Director"),
      r("Action Unit Director"),
      r("Insert Unit Director"),
      r("VFX Unit Director"),
      r("Episode Director"),
      r("Series Director"),
      r("Creative Director"),
      r("Stage Director"),
      r("Theatre Director"),
      role("Script Sup.", "Script Supervisor"),
      role("Cont. Sup.", "Continuity Supervisor"),
      role("Script Coord.", "Script Coordinator"),
      r("Director's Assistant"),
      r("Director's Attaché"),
      r("Shadow Director"),
    ],
  },
  {
    category: "Assistant directing (AD)",
    roles: [
      role("1st AD", "First Assistant Director"),
      role("2nd AD", "Second Assistant Director"),
      role("2nd 2nd AD", "Second Second Assistant Director"),
      role("3rd AD", "Third Assistant Director"),
      role("Floor AD", "Floor Assistant Director"),
      role("Crowd AD", "Crowd Assistant Director"),
      role("Key 2nd AD", "Key Second Assistant Director"),
      role("Basecamp AD", "Basecamp Assistant Director"),
      role("Trainee AD", "Trainee Assistant Director"),
      role("Set AD", "Set Assistant Director"),
      role("Additional AD", "Additional Assistant Director"),
      r("AD Coordinator"),
    ],
  },
  {
    category: "Producing",
    roles: [
      role("EP", "Executive Producer"),
      r("Co-Executive Producer"),
      r("Producer"),
      r("Co-Producer"),
      role("Line Prod.", "Line Producer"),
      r("Associate Producer"),
      r("Assistant Producer"),
      r("Supervising Producer"),
      r("Consulting Producer"),
      r("Consulting EP"),
      r("Segment Producer"),
      r("Field Producer"),
      r("Series Producer"),
      r("Creative Producer"),
      r("Development Producer"),
      r("Impact Producer"),
      role("Post Prod.", "Post Producer"),
      r("Production Executive"),
      r("Studio Executive"),
      r("Showrunner"),
      r("Co-Showrunner"),
      r("Producer's Assistant"),
      r("EP Assistant"),
      r("Financing Producer"),
      r("Investor / Equity Partner"),
      r("Presenter (Production Credit)"),
      r("In Association With"),
    ],
  },
  {
    category: "Writing & story",
    roles: [
      r("Writer"),
      r("Co-Writer"),
      r("Screenwriter"),
      r("Teleplay By"),
      r("Story By"),
      r("Screenplay By"),
      r("Written By"),
      r("Created By"),
      r("Developed By"),
      r("Based On"),
      r("Adaptation By"),
      r("Script Editor"),
      r("Story Editor"),
      r("Executive Story Editor"),
      r("Script Consultant"),
      r("Story Consultant"),
      r("Story Producer"),
      r("Head Writer"),
      r("Staff Writer"),
      r("Freelance Writer"),
      r("Writers' Room"),
      r("Writers' Assistant"),
      r("Script Reader"),
      r("Researchers / Story Research"),
      r("Fact Checker"),
      r("Archival Researcher"),
      r("Translator (Script)"),
      r("Dialogue Coach (Writing)"),
      r("Joke Writer"),
      r("Sketch Writer"),
    ],
  },
  {
    category: "Camera & cinematography",
    roles: [
      role("DOP", "Director of Photography"),
      r("Cinematographer"),
      r("Additional DOP"),
      r("2nd Unit DOP"),
      r("Camera Operator"),
      role("A Cam Op.", "A Camera Operator"),
      role("B Cam Op.", "B Camera Operator"),
      role("C Cam Op.", "C Camera Operator"),
      role("D Cam Op.", "D Camera Operator"),
      role("Steadicam Op.", "Steadicam Operator"),
      role("Gimbal Op.", "Gimbal Operator"),
      role("Handheld Op.", "Handheld Camera Operator"),
      role("Drone Op.", "Drone Operator"),
      role("Drone Pilot", "UAV / Drone Pilot"),
      role("U/W DOP", "Underwater Director of Photography"),
      r("Underwater Camera Operator"),
      r("Aerial Camera Operator"),
      r("Helicopter Camera Operator"),
      r("Crane Operator (Camera)"),
      r("Techno Crane Operator"),
      r("Remote Head Operator"),
      r("Russian Arm Operator"),
      role("1st AC", "First Assistant Camera / Focus Puller"),
      role("2nd AC", "Second Assistant Camera / Clapper Loader"),
      role("3rd AC", "Third Assistant Camera"),
      role("DIT", "Digital Imaging Technician"),
      r("Data Wrangler"),
      r("Loader"),
      role("VT", "Video Assist / Video Technician"),
      r("Video Playback"),
      r("QTake Operator"),
      r("Camera PA"),
      r("Camera Trainee"),
      role("Dolly Grip", "Dolly Grip (Camera Support)"),
      r("Libra Head Technician"),
      r("Still Photographer (Unit)"),
      r("BTS Camera Operator"),
      r("Multi-Cam Director"),
      r("Vision Mixer / Technical Director"),
      r("Shader / CCU Operator"),
    ],
  },
  {
    category: "Lighting (grip & electric)",
    roles: [
      r("Gaffer"),
      role("BBE", "Best Boy Electric"),
      r("Lighting Technician"),
      r("Electrician"),
      r("Set Electrician"),
      r("Rigging Gaffer"),
      r("Rigging Electrician"),
      r("Generator Operator"),
      r("Dimmer Board Operator"),
      r("Lighting Console Programmer"),
      r("Practical Lighting Technician"),
      role("Key Grip", "Key Grip"),
      role("BBG", "Best Boy Grip"),
      r("Grip"),
      r("Company Grip"),
      r("Rigging Grip"),
      r("Scaffolding Grip"),
      r("Crane Grip"),
      r("Remote Head Grip"),
      r("Lamp Operator"),
      r("Balloon Lighting Technician"),
      r("HMI Technician"),
      r("LED Technician"),
    ],
  },
  {
    category: "Sound — production",
    roles: [
      role("Sound Mixer", "Production Sound Mixer"),
      r("Location Sound Recordist"),
      r("Boom Operator"),
      r("Sound Assistant"),
      r("Utility Sound"),
      r("Sound Trainee"),
      r("Playback Operator"),
      r("Wireman / Radio Mic Tech"),
      r("Sound Utility"),
      r("Music Playback"),
      r("Live Sound Engineer"),
      r("RF Coordinator"),
    ],
  },
  {
    category: "Art department",
    roles: [
      r("Production Designer"),
      r("Co-Production Designer"),
      r("Art Director"),
      r("Supervising Art Director"),
      r("Assistant Art Director"),
      r("Set Designer"),
      r("Assistant Set Designer"),
      r("Draftsperson / Draughtsperson"),
      r("Set Decorator"),
      r("Assistant Set Decorator"),
      r("Lead Set Dresser"),
      r("Set Dresser"),
      r("On-Set Dresser"),
      r("Swing Gang"),
      r("Props Master"),
      r("Assistant Props"),
      r("Props Buyer"),
      r("Prop Maker"),
      r("Prop Builder"),
      r("Weapons Props"),
      r("Action Props"),
      r("Greensman"),
      r("Greens Coordinator"),
      r("Construction Coordinator"),
      r("Construction Foreman"),
      r("Carpenter"),
      r("Lead Carpenter"),
      r("Scenic Artist"),
      r("Scenic Painter"),
      r("Charge Scenic"),
      r("Plasterer"),
      r("Sculptor (Art)"),
      r("Model Maker"),
      r("Graphic Designer (Art)"),
      r("Sign Writer"),
      r("Art Department Coordinator"),
      r("Art Department PA"),
      r("Art Department Researcher"),
      r("Concept Artist (Art)"),
      r("Storyboard Artist"),
      r("Illustrator"),
    ],
  },
  {
    category: "Wardrobe, hair & makeup",
    roles: [
      r("Costume Designer"),
      r("Assistant Costume Designer"),
      r("Costume Supervisor"),
      r("Wardrobe Supervisor"),
      r("Wardrobe Assistant"),
      r("On-Set Costumer"),
      r("Costumer"),
      r("Costume Buyer"),
      r("Costume Illustrator"),
      r("Tailor / Seamstress"),
      r("Cutter"),
      r("Costume Breakdown Artist"),
      r("Costume PA"),
      role("HMU Sup.", "Hair & Makeup Supervisor"),
      r("Key Makeup Artist"),
      r("Key Hair Stylist"),
      r("Makeup Artist"),
      r("Hair Stylist"),
      r("Assistant Makeup Artist"),
      r("Assistant Hair Stylist"),
      r("SFX Makeup Artist"),
      r("Prosthetics Artist"),
      r("Prosthetics Designer"),
      r("Body Makeup Artist"),
      r("Crowd Makeup"),
      r("Crowd Hair"),
      r("Barber"),
      r("Groomer"),
      r("Wig Maker"),
      r("Wig Stylist"),
    ],
  },
  {
    category: "Casting",
    roles: [
      r("Casting Director"),
      r("Casting Associate"),
      r("Casting Assistant"),
      r("Casting Coordinator"),
      r("Extras Casting"),
      r("Local Casting Director"),
      r("Voice Casting Director"),
      r("Casting Producer"),
      r("Talent Booker"),
      r("Background Casting"),
    ],
  },
  {
    category: "Production & locations",
    roles: [
      r("Unit Production Manager"),
      r("Production Manager"),
      r("Assistant Production Manager"),
      r("Production Coordinator"),
      r("Assistant Production Coordinator"),
      r("Production Secretary"),
      r("Production Accountant"),
      r("First Assistant Accountant"),
      r("Payroll Accountant"),
      r("Assistant Accountant"),
      r("Cashier"),
      r("Location Manager"),
      r("Key Location Manager"),
      r("Assistant Location Manager"),
      r("Location Scout"),
      r("Location Coordinator"),
      r("Location PA"),
      r("Unit Manager"),
      r("Basecamp Manager"),
      r("Travel Coordinator"),
      r("Accommodation Coordinator"),
      r("Shipping Coordinator"),
      r("Clearances Coordinator"),
      r("Production Assistant (PA)"),
      r("Set PA"),
      r("Office PA"),
      r("Key PA"),
      r("Runner"),
      r("Reception / Front Desk"),
      r("Production Office Manager"),
      r("Studio Manager"),
    ],
  },
  {
    category: "Post production — editorial",
    roles: [
      r("Editor"),
      r("Co-Editor"),
      r("Supervising Editor"),
      role("AE", "Assistant Editor"),
      r("First Assistant Editor"),
      r("Second Assistant Editor"),
      r("Assembly Editor"),
      r("Offline Editor"),
      r("Online Editor"),
      r("Conform Editor"),
      r("Trailer Editor"),
      r("Promo Editor"),
      r("Additional Editor"),
      r("Post Production Supervisor"),
      r("Post Production Producer"),
      r("Post Production Coordinator"),
      r("Post Production Assistant"),
      r("Post PA"),
      r("Edit Bay Coordinator"),
      r("Dailies Producer"),
      r("Dailies Technician"),
    ],
  },
  {
    category: "Post production — picture & colour",
    roles: [
      r("Colorist"),
      r("Colourist"),
      role("DI Colourist", "DI / Digital Intermediate Colourist"),
      r("Assistant Colorist"),
      r("Finishing Artist"),
      r("Online Conform"),
      r("Mastering Technician"),
      r("Deliverables Manager"),
      r("QC Operator"),
      r("QC Supervisor"),
      r("HDR Colorist"),
      r("Film Lab Timer"),
      r("Telecine Colorist"),
      r("Dailies Colorist"),
    ],
  },
  {
    category: "Sound — post",
    roles: [
      r("Sound Designer"),
      r("Supervising Sound Editor"),
      r("Dialogue Editor"),
      r("Dialogue Supervisor"),
      r("ADR Supervisor"),
      r("ADR Mixer"),
      r("ADR Recordist"),
      r("ADR Editor"),
      r("Foley Artist"),
      r("Foley Mixer"),
      r("Foley Editor"),
      r("Foley Walker"),
      role("RX / Restoration", "Audio Restoration / RX"),
      role("Re-recording Mixer", "Re-Recording Mixer"),
      r("Dubbing Mixer"),
      r("Sound Effects Editor"),
      r("SFX Editor"),
      r("Backgrounds Editor"),
      r("Music Editor"),
      r("Temp Music Editor"),
      r("Mix Assistant"),
      r("Sound Intern"),
    ],
  },
  {
    category: "Visual effects & animation",
    roles: [
      role("VFX Sup.", "VFX Supervisor"),
      r("On-Set VFX Supervisor"),
      r("VFX Producer"),
      r("VFX Coordinator"),
      r("VFX Editor"),
      r("VFX Plate Supervisor"),
      r("Compositor"),
      r("Lead Compositor"),
      r("CGI Artist"),
      r("CG Supervisor"),
      r("FX TD"),
      r("Lighting TD"),
      r("Lookdev Artist"),
      r("Texture Artist"),
      r("Modeler"),
      r("Character TD"),
      r("Animator"),
      r("Lead Animator"),
      r("Character Animator"),
      r("Layout Artist"),
      r("Matte Painter"),
      r("Environment Artist"),
      r("Roto Artist"),
      r("Paint Artist"),
      r("Matchmove Artist"),
      r("Tracking Artist"),
      r("Previs Artist"),
      r("Previs Supervisor"),
      r("Postvis Artist"),
      r("Concept Artist (VFX)"),
      r("VFX Data Wrangler"),
      r("Lidar Technician"),
      r("Photogrammetry Artist"),
      r("Animation Director"),
      r("Animation Producer"),
      r("Storyboard Artist (Animation)"),
      r("Clean-up Artist"),
      r("Inbetween Artist"),
      r("Color Key Artist"),
      r("Background Painter"),
    ],
  },
  {
    category: "Music",
    roles: [
      r("Composer"),
      r("Co-Composer"),
      r("Additional Music"),
      r("Theme Music"),
      r("Music Supervisor"),
      r("Music Producer"),
      r("Music Contractor"),
      r("Music Coordinator"),
      r("Orchestrator"),
      r("Music Arranger"),
      r("Conductor"),
      r("Score Mixer"),
      r("Score Recordist"),
      r("Music Clearance"),
      r("Songwriter"),
      r("Lyricist"),
      r("Featured Artist (Music)"),
      r("Session Musician"),
      r("Choir Director"),
      r("Music Librarian"),
    ],
  },
  {
    category: "Stunts, action & intimacy",
    roles: [
      r("Stunt Coordinator"),
      r("Assistant Stunt Coordinator"),
      r("Fight Coordinator"),
      r("Martial Arts Choreographer"),
      r("Action Choreographer"),
      r("Wire Team Coordinator"),
      r("Wire Rigger"),
      r("Intimacy Coordinator"),
      r("Intimacy Assistant"),
      r("Armorer"),
      r("Weapons Master"),
      r("Weapons Handler"),
      r("Pyrotechnician"),
      r("SFX Supervisor (On Set)"),
      r("Special Effects Technician"),
      r("Practical Effects"),
      r("Rain / Weather Effects"),
      r("Fire Safety Officer"),
    ],
  },
  {
    category: "Documentary, factual & unscripted",
    roles: [
      r("Series Editor (Factual)"),
      r("Executive Editor"),
      r("Development Executive"),
      r("Commissioning Editor"),
      r("Director / Producer (Doc)"),
      r("Self-Shooting Producer"),
      r("Self-Shooting Director"),
      r("Fixer"),
      r("Local Fixer"),
      r("Field Director"),
      r("Archive Producer"),
      r("Archive Researcher"),
      r("Researcher"),
      r("Senior Researcher"),
      r("Junior Researcher"),
      r("Impact Campaign Lead"),
      r("Outreach Producer"),
      r("Character Producer"),
      r("Cast Producer (Unscripted)"),
      r("Story Producer (Unscripted)"),
      r("Edit Producer"),
      r("Offline Producer"),
      r("Compliance Producer"),
      r("Apologies / Clearance Producer"),
      r("Gallery Producer"),
      r("Floor Manager"),
      r("Studio Director"),
      r("Prompt Operator"),
      r("Autocue Operator"),
      r("Warm-Up Artist"),
    ],
  },
  {
    category: "Nature, wildlife & science",
    roles: [
      r("Natural History Producer"),
      r("Wildlife Cameraman"),
      r("Wildlife Camera Operator"),
      r("Specialist Nature DOP"),
      r("Underwater Wildlife Camera"),
      r("Macro Photographer / Camera"),
      r("Scientific Advisor"),
      r("Field Guide / Tracker"),
      r("Conservation Advisor"),
      r("Animal Behaviourist"),
      r("Expedition Leader"),
      r("Camp Manager (Field)"),
    ],
  },
  {
    category: "Specialty & support",
    roles: [
      r("Choreographer"),
      r("Assistant Choreographer"),
      r("Dialect Coach"),
      r("Acting Coach"),
      r("Dialogue Coach"),
      r("Movement Coach"),
      r("Animal Wrangler"),
      r("Horse Master"),
      r("Marine Coordinator"),
      r("Aerial Coordinator"),
      r("Helicopter Pilot"),
      r("Transportation Coordinator"),
      r("Transport Captain"),
      r("Unit Driver"),
      r("Picture Car Coordinator"),
      r("Picture Vehicle Wrangler"),
      r("Craft Services"),
      r("Catering"),
      r("Chef / Unit Chef"),
      r("Set Medic"),
      r("Paramedic"),
      r("Nurse (Unit)"),
      r("Health & Safety Officer"),
      r("Safety Supervisor"),
      r("COVID Compliance Officer"),
      r("Security"),
      r("Close Protection"),
      r("Still Photographer"),
      role("EPK", "EPK / Behind-the-Scenes"),
      r("BTS Producer"),
      r("Unit Publicist"),
      r("Publicity Coordinator"),
      r("Social Media Manager"),
      r("Digital Content Producer"),
      r("Archival Producer"),
      r("Legal / Entertainment Lawyer"),
      r("Business Affairs"),
      r("Contracts Manager"),
      r("Titles Designer"),
      r("Motion Graphics Designer"),
      r("Graphic Designer (Titles)"),
      r("Subtitling / Localization"),
      r("Translator"),
      r("Interpreter"),
      r("Accessibility Coordinator"),
      r("Audio Description Writer"),
      r("SDHD / Captions"),
      r("Distributor Representative"),
      r("Sales Agent"),
      r("Festival Strategist"),
      r("Marketing Producer"),
      r("Trailer Producer"),
      r("Key Art Designer"),
      r("Consultant"),
      r("Technical Advisor"),
      r("Military Advisor"),
      r("Medical Advisor"),
      r("Cultural Consultant"),
      r("Sensitivity Reader"),
      r("Community Liaison"),
      r("Intern"),
      r("Trainee"),
      r("Volunteer"),
      r("Other"),
    ],
  },
];

/** Flat list of every credit option (deduped by value). */
export const UPLOAD_CREDIT_ROLES_FLAT: UploadCreditRole[] = (() => {
  const seen = new Set<string>();
  const out: UploadCreditRole[] = [];
  for (const group of UPLOAD_CREDIT_ROLE_GROUPS) {
    for (const item of group.roles) {
      if (seen.has(item.value)) continue;
      seen.add(item.value);
      out.push(item);
    }
  }
  return out;
})();

export function isKnownUploadCreditRole(value: string): boolean {
  return UPLOAD_CREDIT_ROLES_FLAT.some((r) => r.value === value);
}
