/**
 * MODOC — Machine Orchestrating Digital Operations for Creation
 * Platform-wide AI assistant for Story Time.
 */

export {
  buildModocSystemPrompt,
  MODOC_IDENTITY,
  PLATFORM_SUMMARY,
  MODOC_IDEA_DEVELOPMENT_INSTRUCTIONS,
  MODOC_SCRIPT_WRITING_INSTRUCTIONS,
  MODOC_TASK_LOGLINE,
  MODOC_TASK_IDEA_NOTES,
  MODOC_TASK_SCRIPT,
  MODOC_TASK_SCRIPT_REVIEW,
  MODOC_TASK_SCRIPT_BREAKDOWN,
  MODOC_TASK_BUDGET,
  MODOC_TASK_SCHEDULE,
  MODOC_TASK_LOCATION_MARKETPLACE,
  MODOC_TASK_EQUIPMENT_PLANNING,
  MODOC_TASK_CASTING_PORTAL,
  MODOC_TASK_CREW_MARKETPLACE,
  MODOC_TASK_VISUAL_PLANNING,
  MODOC_TASK_LEGAL_CONTRACTS,
  MODOC_TASK_FUNDING_HUB,
  MODOC_TASK_PITCH_DECK,
  MODOC_TASK_TABLE_READS,
  MODOC_TASK_PRODUCTION_WORKSPACE,
  MODOC_TASK_RISK_INSURANCE,
  MODOC_TASK_PRODUCTION_READINESS,
  MODOC_TASK_PRODUCTION_CONTROL_CENTER,
  MODOC_TASK_CALL_SHEET_GENERATOR,
  MODOC_TASK_ON_SET_TASKS,
  MODOC_TASK_EQUIPMENT_TRACKING,
  MODOC_TASK_SHOOT_PROGRESS,
  MODOC_TASK_CONTINUITY_MANAGER,
  MODOC_TASK_DAILIES_REVIEW,
  MODOC_TASK_PRODUCTION_EXPENSE_TRACKER,
  MODOC_TASK_INCIDENT_REPORTING,
  MODOC_TASK_PRODUCTION_WRAP,
  MODOC_TASK_CREATOR_ANALYTICS,
} from "./system-prompt";
export type {
  ModocChatMessage,
  ModocChatRequest,
  ModocPlatformContext,
  ModocUserContext,
} from "./types";
