import { prisma } from "@/lib/prisma";
import type { PdfBlock } from "@/lib/pdf/document-pdf";
import { buildDocumentPdf } from "@/lib/pdf/document-pdf";
import type { ContractHireSettlementQuote } from "@/lib/payments/contract-hire-settlement";
import { parseEmbeddedMeta, embedMeta } from "@/lib/marketplace-profile-meta";
import type { ExpenseMeta } from "@/lib/expense-types";

export type ContractHireReceiptAudience = "creator" | "payee" | "admin";

export function contractHireReceiptNumber(transactionId: string): string {
  return `ST-HIRE-${transactionId.slice(-10).toUpperCase()}`;
}

export async function syncContractHireReceiptSnapshots(
  quote: ContractHireSettlementQuote,
  transactionId: string,
  paymentRecordId?: string,
) {
  const receiptNumber = contractHireReceiptNumber(transactionId);
  const snapshot = {
    receiptNumber,
    transactionId,
    contractId: quote.contractId,
    projectId: quote.projectId,
    projectTitle: quote.projectTitle,
    payeeLabel: quote.payeeLabel,
    baseAmount: quote.baseAmount,
    platformFeeAmount: quote.platformFeeAmount,
    totalAmount: quote.totalAmount,
    gatewayFeeEstimate: quote.gatewayFeeEstimate,
    paidAt: new Date().toISOString(),
  };

  if (paymentRecordId) {
    const record = await prisma.paymentRecord.findUnique({
      where: { id: paymentRecordId },
      select: { metadata: true },
    });
    const meta =
      record?.metadata && typeof record.metadata === "object"
        ? (record.metadata as Record<string, unknown>)
        : {};
    await prisma.paymentRecord.update({
      where: { id: paymentRecordId },
      data: {
        metadata: { ...meta, contractHireReceipt: snapshot },
      },
    });
  }

  const expense = await prisma.productionExpense.findMany({
    where: { projectId: quote.projectId },
    include: { createdBy: { select: { id: true, name: true, email: true } } },
    orderBy: { createdAt: "desc" },
    take: 50,
  });
  const matched = expense
    .map((row) => {
      const parsed = parseEmbeddedMeta<ExpenseMeta>(row.description);
      return { row, meta: parsed.meta };
    })
    .find(
      (e) =>
        e.meta?.autoGeneratedFrom === `contract_hire:${quote.contractId}` ||
        e.meta?.linkedContractId === quote.contractId,
    );
  if (matched?.row.description) {
    try {
      const parsed = parseEmbeddedMeta<ExpenseMeta>(matched.row.description);
      const meta = { ...(parsed.meta ?? {}), receiptNumber, linkedMarketplaceTransactionId: transactionId };
      await prisma.productionExpense.update({
        where: { id: matched.row.id },
        data: { description: embedMeta(parsed.plain, meta as Record<string, unknown>) },
      });
    } catch {
      /* ignore */
    }
  }
}

export function buildContractHireReceiptBlocks(args: {
  receiptNumber: string;
  audience: ContractHireReceiptAudience;
  projectTitle: string;
  contractId: string;
  payeeLabel: string;
  payerLabel: string;
  baseAmount: number;
  platformFeeAmount: number;
  gatewayFeeAmount: number;
  totalAmount: number;
  paidAt: Date;
  transactionId: string;
}): PdfBlock[] {
  const dateStr = args.paidAt.toLocaleString("en-ZA", { timeZone: "Africa/Johannesburg" });
  const audienceNote =
    args.audience === "creator"
      ? "Creator copy — salary disbursement confirmation"
      : args.audience === "payee"
        ? "Payee copy — funds credited to your Story Time wallet (monthly payout)"
        : "Admin copy — treasury and fee routing record";

  return [
    { type: "title", text: "Story Time — Contract hire payment receipt" },
    { type: "subtitle", text: audienceNote },
    { type: "blank" },
    { type: "kv", label: "Receipt #", value: args.receiptNumber },
    { type: "kv", label: "Transaction", value: args.transactionId },
    { type: "kv", label: "Contract", value: args.contractId },
    { type: "kv", label: "Project", value: args.projectTitle },
    { type: "kv", label: "Paid at", value: dateStr },
    { type: "heading", text: "Parties" },
    { type: "kv", label: "Payer (production)", value: args.payerLabel },
    { type: "kv", label: "Payee", value: args.payeeLabel },
    { type: "heading", text: "Amount breakdown (ZAR)" },
    {
      type: "table",
      headers: ["Line", "Amount"],
      rows: [
        ["Contract salary (payee receives)", `R ${args.baseAmount.toFixed(2)}`],
        ["Story Time platform fee (3%)", `R ${args.platformFeeAmount.toFixed(2)}`],
        ["PayFast gateway fee (estimate)", `R ${args.gatewayFeeAmount.toFixed(2)}`],
        ["Total charged to creator", `R ${args.totalAmount.toFixed(2)}`],
      ],
    },
    { type: "blank" },
    {
      type: "line",
      text: "Payee earnings are held in pending wallet balance until monthly payout (existing admin payout flow).",
    },
  ];
}

export function buildContractHireReceiptPdf(args: Parameters<typeof buildContractHireReceiptBlocks>[0]): Buffer {
  return buildDocumentPdf({
    title: "Contract hire payment receipt",
    footer: args.receiptNumber,
    blocks: buildContractHireReceiptBlocks(args),
  });
}
