import { prisma } from "@/lib/prisma";
import { computeMarketplaceFeeZar } from "@/lib/marketplace-zar-defaults";
import { postMarketplacePaymentAllocation } from "@/lib/payments/marketplace-allocation";
import { settleMarketplaceWithWallet } from "@/lib/payments/marketplace-wallet";
import { ensureWalletForUser } from "@/lib/payments/wallet";
import { assertFunderVerificationApproved } from "@/lib/funder-verification";
import { createProductionExpense } from "@/lib/expense-service";

export type FundingDealSettlementQuote = {
  dealId: string;
  payerUserId: string;
  payeeUserId: string;
  projectId: string | null;
  baseAmount: number;
  feeAmount: number;
  totalAmount: number;
  transactionType: "INVESTMENT_DEAL";
  escrowIdempotencyKey: string;
  purpose: "INVESTMENT_DEAL";
};

export async function resolveFundingDealSettlement(
  dealId: string,
  funderUserId: string,
  amountOverride?: number,
): Promise<{ ok: true; quote: FundingDealSettlementQuote } | { ok: false; error: string; status: number }> {
  const verified = await assertFunderVerificationApproved(funderUserId);
  if (!verified.ok) {
    return { ok: false, error: verified.error, status: 403 };
  }

  const deal = await prisma.investmentDeal.findUnique({
    where: { id: dealId },
    include: {
      termSheets: { orderBy: { createdAt: "desc" }, take: 1 },
      payments: { where: { status: { in: ["AUTHORIZED", "SETTLED"] } }, take: 1 },
    },
  });
  if (!deal) return { ok: false, error: "Deal not found", status: 404 };
  if (deal.funderUserId !== funderUserId) return { ok: false, error: "Forbidden", status: 403 };
  if (deal.payments.length > 0) return { ok: false, error: "Deal already has a completed payment", status: 400 };
  if (!["SIGNING", "CONTRACT_PENDING"].includes(deal.pipelineStatus)) {
    return { ok: false, error: "Deal must be contracted before funding", status: 400 };
  }

  const baseAmount =
    amountOverride && amountOverride > 0
      ? amountOverride
      : deal.termSheets[0]?.investmentAmount ?? 0;
  if (baseAmount <= 0) return { ok: false, error: "Investment amount not set on deal", status: 400 };

  const feeAmount = computeMarketplaceFeeZar(baseAmount);
  const totalAmount = Math.round((baseAmount + feeAmount) * 100) / 100;

  return {
    ok: true,
    quote: {
      dealId,
      payerUserId: funderUserId,
      payeeUserId: deal.creatorUserId,
      projectId: deal.projectId,
      baseAmount,
      feeAmount,
      totalAmount,
      transactionType: "INVESTMENT_DEAL",
      escrowIdempotencyKey: `escrow_hold_investment_${dealId}`,
      purpose: "INVESTMENT_DEAL",
    },
  };
}

export async function finalizeFundingDealWalletPayment(quote: FundingDealSettlementQuote) {
  const walletSettle = await settleMarketplaceWithWallet({
    buyerUserId: quote.payerUserId,
    sellerUserId: quote.payeeUserId,
    baseAmount: quote.baseAmount,
    feeAmount: quote.feeAmount,
    totalAmount: quote.totalAmount,
    referenceType: "InvestmentDeal",
    referenceId: quote.dealId,
    escrowIdempotencyKey: quote.escrowIdempotencyKey,
  });
  if (!walletSettle.ok) {
    return { ok: false as const, error: walletSettle.error };
  }

  const tx = await prisma.transaction.create({
    data: {
      payerId: quote.payerUserId,
      payeeId: quote.payeeUserId,
      amount: quote.baseAmount,
      feeAmount: quote.feeAmount,
      totalAmount: quote.totalAmount,
      status: "COMPLETED",
      type: "INVESTMENT_DEAL",
      referenceId: quote.dealId,
      externalPaymentId: null,
    },
  });

  const payment = await prisma.dealPayment.create({
    data: {
      dealId: quote.dealId,
      initiatedById: quote.payerUserId,
      amount: quote.baseAmount,
      status: "SETTLED",
      gatewayProvider: "WALLET",
      paymentTransactionId: tx.id,
      settledAt: new Date(),
      metadata: {
        platformFee: quote.feeAmount,
        totalCharged: quote.totalAmount,
      },
    },
  });

  await prisma.investmentDeal.update({
    where: { id: quote.dealId },
    data: { pipelineStatus: "FUNDED", closedAt: new Date() },
  });

  if (quote.projectId) {
    try {
      await createProductionExpense({
        projectId: quote.projectId,
        userId: quote.payeeUserId,
        amount: quote.baseAmount,
        title: "Investment received",
        category: "MISCELLANEOUS",
        vendor: "Funder (platform)",
        paymentMethod: "TRANSFER",
        paymentStatus: "PAID",
        approvalStatus: "APPROVED",
        notes: `Investment deal ${quote.dealId} · txn ${tx.id}`,
        linkedMarketplaceTransactionId: tx.id,
        autoGeneratedFrom: `investment_deal:${quote.dealId}`,
        skipDuplicateCheck: true,
        forceCreate: true,
      });
    } catch {
      /* non-blocking */
    }
  }

  return {
    ok: true as const,
    transactionId: tx.id,
    paymentId: payment.id,
    paymentMode: "wallet" as const,
    baseAmount: quote.baseAmount,
    feeAmount: quote.feeAmount,
    totalAmount: quote.totalAmount,
  };
}

export async function finalizeFundingDealGatewayPayment(paymentRecordId: string, quote: FundingDealSettlementQuote) {
  await postMarketplacePaymentAllocation({
    payerUserId: quote.payerUserId,
    sellerUserId: quote.payeeUserId,
    baseAmount: quote.baseAmount,
    feeAmount: quote.feeAmount,
    totalAmount: quote.totalAmount,
    referenceType: "InvestmentDeal",
    referenceId: quote.dealId,
    idempotencyKey: `gateway_investment_${paymentRecordId}`,
    paymentSource: "gateway",
    paymentRecordId,
  });

  const buyerWallet = await ensureWalletForUser(quote.payerUserId);
  const sellerWallet = await ensureWalletForUser(quote.payeeUserId);
  await (prisma as { escrowAccount: { upsert: (args: unknown) => Promise<unknown> } }).escrowAccount.upsert({
    where: {
      referenceType_referenceId: {
        referenceType: "InvestmentDeal",
        referenceId: quote.dealId,
      },
    },
    create: {
      referenceType: "InvestmentDeal",
      referenceId: quote.dealId,
      buyerWalletId: buyerWallet.id,
      sellerWalletId: sellerWallet.id,
      amount: quote.baseAmount,
      status: "RELEASED",
      releaseTrigger: "MONTHLY_VENDOR_PAYOUT",
      releasedAt: new Date(),
    },
    update: {
      status: "RELEASED",
      amount: quote.baseAmount,
      releasedAt: new Date(),
    },
  });

  const tx = await prisma.transaction.create({
    data: {
      payerId: quote.payerUserId,
      payeeId: quote.payeeUserId,
      amount: quote.baseAmount,
      feeAmount: quote.feeAmount,
      totalAmount: quote.totalAmount,
      status: "COMPLETED",
      type: "INVESTMENT_DEAL",
      referenceId: quote.dealId,
      externalPaymentId: paymentRecordId,
    },
  });

  await prisma.dealPayment.create({
    data: {
      dealId: quote.dealId,
      initiatedById: quote.payerUserId,
      amount: quote.baseAmount,
      status: "SETTLED",
      gatewayProvider: "PAYFAST",
      gatewayReference: paymentRecordId,
      paymentTransactionId: tx.id,
      settledAt: new Date(),
      metadata: {
        platformFee: quote.feeAmount,
        totalCharged: quote.totalAmount,
      },
    },
  });

  await prisma.investmentDeal.update({
    where: { id: quote.dealId },
    data: { pipelineStatus: "FUNDED", closedAt: new Date() },
  });

  if (quote.projectId) {
    try {
      await createProductionExpense({
        projectId: quote.projectId,
        userId: quote.payeeUserId,
        amount: quote.baseAmount,
        title: "Investment received",
        category: "MISCELLANEOUS",
        vendor: "Funder (platform)",
        paymentMethod: "TRANSFER",
        paymentStatus: "PAID",
        approvalStatus: "APPROVED",
        notes: `Investment deal ${quote.dealId} · gateway ${paymentRecordId}`,
        linkedMarketplaceTransactionId: tx.id,
        autoGeneratedFrom: `investment_deal:${quote.dealId}`,
        skipDuplicateCheck: true,
        forceCreate: true,
      });
    } catch {
      /* non-blocking */
    }
  }

  return { ok: true as const, transactionId: tx.id, paymentMode: "gateway" as const };
}
