ALTER TABLE "FunderProfile"
ADD COLUMN IF NOT EXISTS "riskLevel" TEXT NOT NULL DEFAULT 'LOW';

ALTER TABLE "FunderProfile"
ADD COLUMN IF NOT EXISTS "submittedAt" TIMESTAMP(3);

ALTER TABLE "FunderProfile"
ADD COLUMN IF NOT EXISTS "kycData" JSONB NOT NULL DEFAULT '{}';
