import { NextRequest, NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { parseEmbeddedMeta, embedMeta } from "@/lib/marketplace-profile-meta";
import { validateStorageUrlList } from "@/lib/storage-origin";

async function ensureExpenseAccess(projectId: string) {
  const session = await getServerSession(authOptions);
  const role = (session?.user as { role?: string })?.role;
  const userId = (session?.user as { id?: string })?.id;

  if (!session || !userId || (role !== "CONTENT_CREATOR" && role !== "ADMIN")) {
    return { error: NextResponse.json({ error: "Unauthorized" }, { status: 401 }), userId: null as string | null };
  }

  const project = await prisma.originalProject.findUnique({
    where: { id: projectId },
    include: { members: true, pitches: true },
  });

  if (!project) {
    return { error: NextResponse.json({ error: "Not found" }, { status: 404 }), userId: null as string | null };
  }

  const isCreatorMember =
    role === "ADMIN" ||
    project.members.some((m) => m.userId === userId) ||
    project.pitches.some((p) => p.creatorId === userId);

  if (!isCreatorMember) {
    return { error: NextResponse.json({ error: "Forbidden" }, { status: 403 }), userId: null as string | null };
  }

  return { error: null as NextResponse | null, userId };
}

type ExpenseCategory =
  | "CAST"
  | "CREW"
  | "EQUIPMENT"
  | "LOCATIONS"
  | "TRANSPORT"
  | "CATERING"
  | "POST_PRODUCTION"
  | "MISCELLANEOUS";

type ExpenseMeta = {
  title?: string | null;
  category?: ExpenseCategory | string | null;
  sceneId?: string | null;
  shootDayId?: string | null;
  paymentMethod?: "CASH" | "TRANSFER" | "CARD" | "MOBILE" | "OTHER" | null;
  notes?: string | null;
  receiptUrls?: string[];
  paymentProofUrls?: string[];
  fundingSource?: string | null;
  fundingSourceId?: string | null;
  approvalStatus?: "PENDING" | "APPROVED" | "REJECTED";
  approvalByUserId?: string | null;
  approvalAt?: string | null;
  paymentStatus?: "UNPAID" | "PARTIAL" | "PAID";
  paymentDueAt?: string | null;
  linkedContractId?: string | null;
  linkedEquipmentPlanItemId?: string | null;
  linkedLocationBookingId?: string | null;
  linkedTaskId?: string | null;
  autoGeneratedFrom?: string | null;
  history?: Array<{ at: string; byUserId: string | null; action: string; patch?: Record<string, unknown> }>;
};

function asNum(v: unknown): number {
  const n = Number(v);
  return Number.isFinite(n) ? n : 0;
}

export async function GET(
  req: NextRequest,
  context: { params: Promise<{ projectId: string }> },
) {
  const { projectId } = await context.params;
  const access = await ensureExpenseAccess(projectId);
  if (access.error) return access.error;

  const [expensesRaw, budget, funding, shootDays, scenes, incidents, tasks, equipmentPlan, contracts] = await Promise.all([
    prisma.productionExpense.findMany({
      where: { projectId },
      orderBy: { spentAt: "desc" },
      include: {
        createdBy: { select: { id: true, name: true, email: true } },
      },
    }),
    prisma.projectBudget.findUnique({
      where: { projectId },
      include: { lines: true },
    }),
    prisma.fundingRequest.findUnique({ where: { projectId } }),
    prisma.shootDay.findMany({ where: { projectId }, select: { id: true, date: true, status: true } }),
    prisma.projectScene.findMany({ where: { projectId }, select: { id: true, number: true, heading: true } }),
    prisma.incidentReport.findMany({ where: { projectId, resolved: false }, select: { id: true, severity: true } }),
    prisma.projectTask.findMany({ where: { projectId }, select: { id: true, status: true, sceneId: true, shootDayId: true } }),
    prisma.equipmentPlanItem.findMany({ where: { projectId }, select: { id: true, quantity: true, notes: true } }),
    prisma.projectContract.findMany({ where: { projectId }, select: { id: true, status: true, subject: true } }),
  ]);

  const expenseRows = expensesRaw.map((e) => {
    const parsed = parseEmbeddedMeta<ExpenseMeta>(e.description);
    const meta = parsed.meta ?? {};
    return {
      id: e.id,
      projectId: e.projectId,
      budgetLineId: e.budgetLineId,
      department: e.department,
      vendor: e.vendor,
      description: parsed.plain,
      amount: e.amount,
      spentAt: e.spentAt.toISOString(),
      createdAt: e.createdAt.toISOString(),
      createdBy: e.createdBy ? { id: e.createdBy.id, name: e.createdBy.name, email: e.createdBy.email } : null,
      meta: {
        title: meta.title ?? parsed.plain ?? "Expense",
        category: meta.category ?? "MISCELLANEOUS",
        sceneId: meta.sceneId ?? null,
        shootDayId: meta.shootDayId ?? null,
        paymentMethod: meta.paymentMethod ?? "OTHER",
        notes: meta.notes ?? null,
        receiptUrls: meta.receiptUrls ?? [],
        paymentProofUrls: meta.paymentProofUrls ?? [],
        fundingSource: meta.fundingSource ?? null,
        fundingSourceId: meta.fundingSourceId ?? null,
        approvalStatus: meta.approvalStatus ?? "PENDING",
        approvalByUserId: meta.approvalByUserId ?? null,
        approvalAt: meta.approvalAt ?? null,
        paymentStatus: meta.paymentStatus ?? "UNPAID",
        paymentDueAt: meta.paymentDueAt ?? null,
        linkedContractId: meta.linkedContractId ?? null,
        linkedEquipmentPlanItemId: meta.linkedEquipmentPlanItemId ?? null,
        linkedLocationBookingId: meta.linkedLocationBookingId ?? null,
        linkedTaskId: meta.linkedTaskId ?? null,
        autoGeneratedFrom: meta.autoGeneratedFrom ?? null,
        history: meta.history ?? [],
      },
    };
  });

  const budgetByDept = (budget?.lines ?? []).reduce((acc, line) => {
    const key = (line.department ?? "MISCELLANEOUS").toUpperCase();
    acc[key] = (acc[key] ?? 0) + asNum(line.total ?? asNum(line.quantity) * asNum(line.unitCost));
    return acc;
  }, {} as Record<string, number>);
  const actualByDept = expenseRows.reduce((acc, e) => {
    const key = (e.meta.category ?? e.department ?? "MISCELLANEOUS").toUpperCase();
    acc[key] = (acc[key] ?? 0) + asNum(e.amount);
    return acc;
  }, {} as Record<string, number>);

  const dayById = new Map(shootDays.map((d) => [d.id, d]));
  const sceneById = new Map(scenes.map((s) => [s.id, s]));

  const byDay = expenseRows.reduce((acc, e) => {
    const dayId = e.meta.shootDayId;
    const key = dayId ?? "__unlinked__";
    acc[key] = (acc[key] ?? 0) + asNum(e.amount);
    return acc;
  }, {} as Record<string, number>);
  const byScene = expenseRows.reduce((acc, e) => {
    const sceneId = e.meta.sceneId;
    if (!sceneId) return acc;
    acc[sceneId] = (acc[sceneId] ?? 0) + asNum(e.amount);
    return acc;
  }, {} as Record<string, number>);

  const totalBudget = asNum(budget?.totalPlanned);
  const totalSpend = expenseRows.reduce((s, e) => s + asNum(e.amount), 0);
  const remainingFunds = Math.max(0, totalBudget - totalSpend);
  const fundingLimit = asNum(funding?.amount);
  const burnByDay = Object.entries(
    expenseRows.reduce((acc, e) => {
      const key = e.spentAt.slice(0, 10);
      acc[key] = (acc[key] ?? 0) + asNum(e.amount);
      return acc;
    }, {} as Record<string, number>),
  )
    .sort((a, b) => a[0].localeCompare(b[0]))
    .map(([date, amount]) => ({ date, amount }));
  const avgBurn = burnByDay.length > 0 ? burnByDay.reduce((s, b) => s + b.amount, 0) / burnByDay.length : 0;
  const topCostDrivers = Object.entries(actualByDept)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 5)
    .map(([category, amount]) => ({ category, amount }));

  const unpaidCount = expenseRows.filter((e) => e.meta.paymentStatus !== "PAID").length;
  const pendingApproval = expenseRows.filter((e) => e.meta.approvalStatus === "PENDING").length;

  const alerts = [
    ...(totalBudget > 0 && totalSpend > totalBudget
      ? [{ type: "BUDGET_OVERRUN", severity: "HIGH", message: `Total spend is over budget by R${(totalSpend - totalBudget).toLocaleString()}.` }]
      : []),
    ...(fundingLimit > 0 && totalSpend > fundingLimit
      ? [{ type: "FUNDING_LIMIT_EXCEEDED", severity: "HIGH", message: `Spend exceeds available funding by R${(totalSpend - fundingLimit).toLocaleString()}.` }]
      : []),
    ...burnByDay
      .filter((d) => d.amount > avgBurn * 1.8 && d.amount > 0)
      .slice(-5)
      .map((d) => ({
        type: "HIGH_SPEND_DAY",
        severity: "MEDIUM",
        message: `High-spend day ${d.date}: R${Math.round(d.amount).toLocaleString()}.`,
      })),
    ...Object.entries(actualByDept)
      .filter(([dept, amount]) => amount > (budgetByDept[dept] ?? 0) && (budgetByDept[dept] ?? 0) > 0)
      .map(([dept, amount]) => ({
        type: "DEPARTMENT_OVERRUN",
        severity: "HIGH",
        message: `${dept.replaceAll("_", " ")} overrun by R${Math.round(amount - (budgetByDept[dept] ?? 0)).toLocaleString()}.`,
      })),
  ];

  const url = new URL(req.url);
  if (url.searchParams.get("format") === "csv") {
    const header = [
      "id","title","category","department","amount","spentAt","vendor","paymentStatus","approvalStatus","scene","shootDay","fundingSource","notes",
    ];
    const lines = [header.join(",")];
    for (const e of expenseRows) {
      const scene = e.meta.sceneId ? sceneById.get(e.meta.sceneId)?.number ?? e.meta.sceneId : "";
      const day = e.meta.shootDayId ? dayById.get(e.meta.shootDayId)?.date.toISOString().slice(0, 10) ?? e.meta.shootDayId : "";
      const row = [
        e.id,
        `${e.meta.title ?? ""}`.replace(/,/g, " "),
        `${e.meta.category ?? ""}`,
        `${e.department ?? ""}`,
        `${e.amount}`,
        `${e.spentAt}`,
        `${e.vendor ?? ""}`.replace(/,/g, " "),
        `${e.meta.paymentStatus ?? ""}`,
        `${e.meta.approvalStatus ?? ""}`,
        `${scene}`,
        `${day}`,
        `${e.meta.fundingSource ?? ""}`.replace(/,/g, " "),
        `${e.meta.notes ?? ""}`.replace(/,/g, " "),
      ];
      lines.push(row.join(","));
    }
    return new NextResponse(lines.join("\n"), {
      headers: {
        "Content-Type": "text/csv; charset=utf-8",
        "Content-Disposition": `attachment; filename="production-expenses-${projectId}.csv"`,
      },
    });
  }

  return NextResponse.json({
    expenses: expenseRows,
    dashboard: {
      totalBudget,
      totalSpend,
      remainingFunds,
      fundingLimit,
      fundingRemaining: fundingLimit > 0 ? Math.max(0, fundingLimit - totalSpend) : null,
      burnRateDaily: avgBurn,
      unpaidCount,
      pendingApproval,
      openIncidents: incidents.length,
      blockedTasks: tasks.filter((t) => t.status === "BLOCKED").length,
      signedContracts: contracts.filter((c) => ["SIGNED", "EXECUTED", "CLOSED"].includes(c.status)).length,
      totalContracts: contracts.length,
      topCostDrivers,
    },
    comparison: {
      byDepartment: Object.keys({ ...budgetByDept, ...actualByDept }).map((dept) => ({
        key: dept,
        budgeted: budgetByDept[dept] ?? 0,
        actual: actualByDept[dept] ?? 0,
        remaining: (budgetByDept[dept] ?? 0) - (actualByDept[dept] ?? 0),
        variance: (budgetByDept[dept] ?? 0) - (actualByDept[dept] ?? 0),
      })),
      byScene: Object.entries(byScene).map(([sceneId, actual]) => ({
        sceneId,
        sceneNumber: sceneById.get(sceneId)?.number ?? sceneId,
        budgeted: 0,
        actual,
        variance: -actual,
      })),
      byProductionDay: Object.entries(byDay).map(([shootDayId, actual]) => ({
        shootDayId,
        date: shootDayId !== "__unlinked__" ? dayById.get(shootDayId)?.date.toISOString() ?? null : null,
        budgeted: 0,
        actual,
        variance: -actual,
      })),
      overall: {
        budgeted: totalBudget,
        actual: totalSpend,
        remaining: totalBudget - totalSpend,
        variance: totalBudget - totalSpend,
      },
    },
    burnRate: burnByDay,
    alerts,
  });
}

export async function POST(
  req: NextRequest,
  context: { params: Promise<{ projectId: string }> },
) {
  const { projectId } = await context.params;
  const access = await ensureExpenseAccess(projectId);
  if (access.error) return access.error;
  const userId = access.userId!;

  const body = (await req.json().catch(() => null)) as
    | {
        action?: "CREATE" | "AUTO_CAPTURE";
        budgetLineId?: string;
        department?: string;
        vendor?: string;
        description?: string;
        amount?: number;
        spentAt?: string;
        title?: string;
        category?: ExpenseCategory | string;
        sceneId?: string | null;
        shootDayId?: string | null;
        paymentMethod?: "CASH" | "TRANSFER" | "CARD" | "MOBILE" | "OTHER";
        notes?: string | null;
        receiptUrls?: string[];
        paymentProofUrls?: string[];
        fundingSource?: string | null;
        fundingSourceId?: string | null;
        approvalStatus?: "PENDING" | "APPROVED" | "REJECTED";
        paymentStatus?: "UNPAID" | "PARTIAL" | "PAID";
        paymentDueAt?: string | null;
        linkedContractId?: string | null;
        linkedEquipmentPlanItemId?: string | null;
        linkedLocationBookingId?: string | null;
        linkedTaskId?: string | null;
        autoSource?:
          | "SIGNED_CONTRACTS"
          | "EQUIPMENT_USAGE"
          | "LOCATION_BOOKINGS"
          | "SCHEDULED_PAYMENTS";
      }
    | null;

  if (!body) {
    return NextResponse.json({ error: "Invalid body" }, { status: 400 });
  }
  if (body.action === "AUTO_CAPTURE") {
    const created: unknown[] = [];
    const now = new Date();
    if (body.autoSource === "SIGNED_CONTRACTS" || !body.autoSource) {
      const contracts = await prisma.projectContract.findMany({
        where: { projectId, status: { in: ["SIGNED", "EXECUTED"] } },
        select: { id: true, type: true, subject: true, vendorName: true },
        take: 20,
      });
      for (const c of contracts) {
        const expense = await prisma.productionExpense.create({
          data: {
            projectId,
            department: c.type.toUpperCase().includes("ACT") ? "CAST" : c.type.toUpperCase().includes("CREW") ? "CREW" : "MISCELLANEOUS",
            vendor: c.vendorName ?? null,
            description: embedMeta(c.subject ?? "Auto-generated contract expense", {
              title: c.subject ?? "Contract expense",
              category: c.type.toUpperCase().includes("ACT") ? "CAST" : c.type.toUpperCase().includes("CREW") ? "CREW" : "MISCELLANEOUS",
              approvalStatus: "APPROVED",
              paymentStatus: "UNPAID",
              linkedContractId: c.id,
              autoGeneratedFrom: "SIGNED_CONTRACTS",
            } as ExpenseMeta),
            amount: 0,
            spentAt: now,
            createdById: userId,
          },
        });
        created.push(expense);
      }
    }
    if (body.autoSource === "EQUIPMENT_USAGE" || !body.autoSource) {
      const items = await prisma.equipmentPlanItem.findMany({
        where: { projectId },
        select: { id: true, category: true, quantity: true, notes: true },
        take: 40,
      });
      for (const item of items) {
        const rate = parseEmbeddedMeta<{ dailyRate?: number | null }>(item.notes).meta?.dailyRate ?? 0;
        if (!rate || rate <= 0) continue;
        const expense = await prisma.productionExpense.create({
          data: {
            projectId,
            department: "EQUIPMENT",
            description: embedMeta(`Auto equipment usage: ${item.category}`, {
              title: `${item.category} usage`,
              category: "EQUIPMENT",
              approvalStatus: "APPROVED",
              paymentStatus: "UNPAID",
              linkedEquipmentPlanItemId: item.id,
              autoGeneratedFrom: "EQUIPMENT_USAGE",
            } as ExpenseMeta),
            amount: rate * Math.max(1, item.quantity),
            spentAt: now,
            createdById: userId,
          },
        });
        created.push(expense);
      }
    }
    return NextResponse.json({ createdCount: created.length, created });
  }

  if (!body?.amount || body.amount <= 0) {
    return NextResponse.json({ error: "Missing amount" }, { status: 400 });
  }

  const meta: ExpenseMeta = {
    title: body.title ?? body.description ?? "Expense",
    category: body.category ?? (body.department as ExpenseCategory | undefined) ?? "MISCELLANEOUS",
    sceneId: body.sceneId ?? null,
    shootDayId: body.shootDayId ?? null,
    paymentMethod: body.paymentMethod ?? "OTHER",
    notes: body.notes ?? null,
    receiptUrls: body.receiptUrls ?? [],
    paymentProofUrls: body.paymentProofUrls ?? [],
    fundingSource: body.fundingSource ?? null,
    fundingSourceId: body.fundingSourceId ?? null,
    approvalStatus: body.approvalStatus ?? "PENDING",
    paymentStatus: body.paymentStatus ?? "UNPAID",
    paymentDueAt: body.paymentDueAt ?? null,
    linkedContractId: body.linkedContractId ?? null,
    linkedEquipmentPlanItemId: body.linkedEquipmentPlanItemId ?? null,
    linkedLocationBookingId: body.linkedLocationBookingId ?? null,
    linkedTaskId: body.linkedTaskId ?? null,
    history: [{ at: new Date().toISOString(), byUserId: userId, action: "CREATE" }],
  };
  const receiptErr = validateStorageUrlList(meta.receiptUrls ?? [], "receiptUrls");
  if (receiptErr) return NextResponse.json({ error: receiptErr }, { status: 400 });
  const proofErr = validateStorageUrlList(meta.paymentProofUrls ?? [], "paymentProofUrls");
  if (proofErr) return NextResponse.json({ error: proofErr }, { status: 400 });

  const expense = await prisma.productionExpense.create({
    data: {
      projectId,
      budgetLineId: body.budgetLineId ?? null,
      department: body.department ?? null,
      vendor: body.vendor ?? null,
      description: embedMeta(body.description ?? null, meta as Record<string, unknown>),
      amount: body.amount,
      spentAt: body.spentAt ? new Date(body.spentAt) : new Date(),
      createdById: userId,
    },
  });

  return NextResponse.json({ expense }, { status: 201 });
}

export async function PATCH(
  req: NextRequest,
  context: { params: Promise<{ projectId: string }> },
) {
  const { projectId } = await context.params;
  const access = await ensureExpenseAccess(projectId);
  if (access.error) return access.error;
  const userId = access.userId;

  const body = (await req.json().catch(() => null)) as
    | {
        id: string;
        amount?: number;
        department?: string | null;
        vendor?: string | null;
        description?: string | null;
        spentAt?: string;
        meta?: Partial<ExpenseMeta>;
      }
    | null;
  if (!body?.id) return NextResponse.json({ error: "Missing id" }, { status: 400 });

  const existing = await prisma.productionExpense.findFirst({ where: { id: body.id, projectId } });
  if (!existing) return NextResponse.json({ error: "Expense not found" }, { status: 404 });

  const parsed = parseEmbeddedMeta<ExpenseMeta>(existing.description);
  const prevMeta = parsed.meta ?? {};
  const history = prevMeta.history ?? [];
  history.push({
    at: new Date().toISOString(),
    byUserId: userId,
    action: "PATCH",
    patch: (body.meta ?? {}) as Record<string, unknown>,
  });
  const nextMeta: ExpenseMeta = { ...prevMeta, ...(body.meta ?? {}), history: history.slice(-50) };
  const receiptErr = validateStorageUrlList(nextMeta.receiptUrls ?? [], "receiptUrls");
  if (receiptErr) return NextResponse.json({ error: receiptErr }, { status: 400 });
  const proofErr = validateStorageUrlList(nextMeta.paymentProofUrls ?? [], "paymentProofUrls");
  if (proofErr) return NextResponse.json({ error: proofErr }, { status: 400 });

  const expense = await prisma.productionExpense.update({
    where: { id: body.id },
    data: {
      ...(body.amount !== undefined ? { amount: body.amount } : {}),
      ...(body.department !== undefined ? { department: body.department } : {}),
      ...(body.vendor !== undefined ? { vendor: body.vendor } : {}),
      ...(body.spentAt !== undefined ? { spentAt: body.spentAt ? new Date(body.spentAt) : existing.spentAt } : {}),
      ...(body.description !== undefined || body.meta !== undefined
        ? { description: embedMeta(body.description ?? parsed.plain, nextMeta as Record<string, unknown>) }
        : {}),
    },
  });

  return NextResponse.json({ expense });
}
